name: Parampreet Walia
author: Parampreet Walia
baseurl: /param-walia
description: theme for jekyll
github: http://www.github.com/param-walia
twitter: http://www.twitter.com/
facebook: http://www.facebook.com
linkedin: http://www.linkedin.com
email: parampreetwalial[at]gmail.com
location: 42°2'16"N   70°12'47"W
disqus: diqus-param-walia

##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
